Implementation of the PDO integration tests suite
prolic/awesomeness pull request #5
Opened 2018-04-26 09:40 UTC by gquemener

As described in https://github.com/prolic/awesomeness/issues/4

2018-04-26 09:51 UTC, prolic requested changes

2018-04-26 09:51 UTC, prolic commented on docker-compose.yml
> +        build: ./pgsql/
that's not needed, you can use something like:
volumes:
- ./src/PdoEventStore/scripts/postgres:/docker-entrypoint-initdb.d

2018-04-26 09:51 UTC, prolic commented on pgsql/Dockerfile
> +FROM postgres:10-alpine
not needed

2018-04-26 09:51 UTC, prolic commented on pgsql/event-store-db.sql
> +CREATE TABLE streams (
not needed

2018-04-26 09:51 UTC, prolic commented on phpunit.xml.dist
> +        <env name="PG_HOST" value="postgres"/>
don't edit this here, copy to phpunit.xml instead (and put to .gitignore), change these values only for yourself.

2018-04-26 09:51 UTC, prolic commented on phpunit.xml.dist
> +        <env name="PG_DBNAME" value="event_store"/>
I think this change here is okay, because of the default postgres script

2018-04-26 09:51 UTC, prolic commented on phpunit.xml.dist
> +        <env name="PG_HOST" value="postgres"/>
I will enable travis with postgres directly, no need for docker on travis

2018-04-27 10:00 UTC, prolic approved these changes

2018-04-27 10:01 UTC, merged

2018-04-27 10:01 UTC, prolic commented
Great @gquemener ! Thank you soooo much

2018-04-27 10:02 UTC, gquemener commented
You're welcome, it was not finished though :thinking: :+1:

2018-04-27 10:03 UTC, prolic commented
Ah no problem, you can push new stuff anytime.